// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Invoiceline {
  produit: string;
  qte: number;
  puht: number;
  tva: number;
  ttc: number;
  taux: number;
}
